[package]
name = "packages"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
diesel = { version = "2.0.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.0.0"
argon2 = "0.5.3"
serde_json = "1.0.142"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.9"

[dependencies.sqlx]
version = "0.7.0"
features = ["sqlite", "runtime-async-std", "migrate"]

[dependencies.rocket_db_pools]
version = "0.2.0"
features = ["sqlx_sqlite"]

[dependencies.rocket_sync_db_pools]
version = "0.1.0"
features = ["diesel_sqlite_pool", "sqlite_pool"]

