name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.13.0

      - name: Build
        working-directory: lang
        run: zig build -Dall=true -Doptimize=ReleaseFast

      - name: Previous Tag
        id: previous_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0

      - name: Copy to website assets
        run: mkdir -p web/static/assets/releases && cp lang/zig-out/bin/intoxicode-* web/static/assets/releases/

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.previous_tag.outputs.tag }}
          files: |
            lang/zig-out/bin/intoxicode-*
